---
language: node_js
node_js:
- 0.1
before_script:
- npm install -g grunt-cli
- make jslib
env:
  global:
  - secure: ! 'Garibk5hJveks68NNN1xG3ZtXoTwl0Zd8ntMoAGA+EysxsCkZ62A3J6TpxO/

      gIAnpNCSN/FjUlJzaoUqiwZglBMV9IB8oVYlgndEK7IUGQjr88fMf3543vI+

      w4OXei6+wIZVkgnGzsswXTaN/UL6O0V5BXvDV8e6HnZ+P9MGMvw='
  - secure: ! 'eRVQBuAT2sc5u4ZgylwRU901yWpSa20+/GIJO7s/tzw5rgjA/MJ1FIgLssUa

      kPILLcIiRypQ8hcjghiM4jqe+lgNepIwrsHWIt5D0bKes23WzDLFqV4vSpxY

      nNhvgG8UG5ccnZZDQ1ZgTvBtyoQDajVrOHwvxmWfp2u4iaiQpfE='
